title: Your Name
author: Your Name
description: Masterâ€™s student in Quantitative Data Science Methods | Research Assistant @ MPI-IS
theme: al-folio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
